### ISSUE TITLE
[Spark][Bug]: NPE If write to MixedHive Format while partition value is NULL 

### ISSUE THREAD

**Issue by baiyangtx** [apache/amoro#1085]
### What happened?

Meet NPE if write to MixedHive format with data contains a NULL value in partition field.

### Affects Versions

0.4.1

### What engines are you seeing the problem on?

Spark

### How to reproduce

```
create table arctic_source3 (id int,name string,salary double,birthday long) using arctic partitioned by (birthday);

 insert overwrite arctic_source3 values ( 1, 'aa', 1.0, NULL )  ;
```

### Relevant log output

```shell
Caused by: java.lang.NullPointerException
        at com.netease.arctic.hive.utils.HivePartitionUtil.partitionValuesAsList(HivePartitionUtil.java:59)
        at com.netease.arctic.hive.op.UpdateHiveFiles.getCreatePartition(UpdateHiveFiles.java:174)
        at com.netease.arctic.hive.op.UpdateHiveFiles.commit(UpdateHiveFiles.java:101)
        at com.netease.arctic.spark.writer.UnkeyedSparkBatchWrite$OverwriteByFilter.commit(UnkeyedSparkBatchWrite.java:220)
        at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2(WriteToDataSourceV2Exec.scala:371)
        ... 31 more

        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
        at org.apache.kyuubi.operation.ExecuteStatement.waitStatementComplete(ExecuteStatement.scala:119)
        at org.apache.kyuubi.operation.ExecuteStatement.$anonfun$runInternal$1(ExecuteStatement.scala:154)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748) (state=,code=0)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
This issue has been removed from milestone 0.5.0 due to it's much more complex then issue description. 
We need a general design to support the Hive default partition feature.

**Comment by wangtaohz** [comment]
> This issue has been removed from milestone 0.5.0 due to it's much more complex then issue description.
> We need a general design to support the Hive default partition feature.

@baiyangtx  Could you elaborate on the complexity? For instance, what are the scenarios we need to take into account?

**Comment by baiyangtx** [comment]
> > This issue has been removed from milestone 0.5.0 due to it's much more complex then issue description.
> > We need a general design to support the Hive default partition feature.
> 
> @baiyangtx Could you elaborate on the complexity? For instance, what are the scenarios we need to take into account?

It's not a problem about spark engine, but a problem about all kind of engines and optimizing. We shoud support the NULL value for partition in mixed-hive.
