### ISSUE TITLE
[Bug][AMS]unit test failed on Windows system

### ISSUE THREAD

**Issue by baiyangtx** [apache/amoro#121]
run command  via git bash 

```
mvn install -pl '!trino' 
```

unit test will failed

```
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 7.277 sec <<< FAILURE!
orphanMetadataFileClean(com.netease.arctic.ams.server.optimize.TestOrphanFileClean)  Time elapsed: 3.959 sec  <<< FAILURE!
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertFalse(Assert.java:65)
        at org.junit.Assert.assertFalse(Assert.java:75)
        at com.netease.arctic.ams.server.optimize.TestOrphanFileClean.orphanMetadataFileClean(TestOrphanFileClean.java:93)


....

Results :

Failed tests:   orphanMetadataFileClean(com.netease.arctic.ams.server.optimize.TestOrphanFileClean)
  orphanDataFileClean(com.netease.arctic.ams.server.optimize.TestOrphanFileClean)

Tests in error:
  testReleaseOptimizer(com.netease.arctic.ams.server.controller.OptimizerControllerTest)
(..)stGetTableList(com.netease.arctic.ams.server.controller.TableControllerTest):
(..)stGetCatalogs(com.netease.arctic.ams.server.controller.TableControllerTest):
(..)stGetDatabaseList(com.netease.arctic.ams.server.controller.TableControllerTest):
(..)stGetOptimizeInfo(com.netease.arctic.ams.server.controller.TableControllerTest):
(..)stGetTableTransactions(com.netease.arctic.ams.server.controller.TableControllerTest):
(..)stGetTransactionDetail(com.netease.arctic.ams.server.controller.TableControllerTest):
(..)stGetTablePartitions(com.netease.arctic.ams.server.controller.TableControllerTest):
(..)stGetPartitionFileListInfo(com.netease.arctic.ams.server.controller.TableControllerTest):
(..)stGetTableDetail(com.netease.arctic.ams.server.controller.TableControllerTest):

Tests run: 35, Failures: 2, Errors: 10, Skipped: 0


[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for arctic-parent 0.3.0:
[INFO]
[INFO] arctic-parent ...................................... SUCCESS [  1.843 s]
[INFO] arctic-ams ......................................... SUCCESS [  0.220 s]
[INFO] arctic-ams-api ..................................... SUCCESS [  1.438 s]
[INFO] arctic-core ........................................ SUCCESS [ 20.968 s]
[INFO] arctic-optimizer ................................... SUCCESS [ 28.756 s]
[INFO] arctic-spark ....................................... SUCCESS [  0.233 s]
[INFO] arctic-spark_3.1 ................................... SUCCESS [01:18 min]
[INFO] arctic-ams-dashboard ............................... SUCCESS [  0.818 s]
[INFO] arctic-ams-server .................................. FAILURE [01:27 min]
[INFO] arctic-flink ....................................... SKIPPED
[INFO] arctic-flink-format-1.12 ........................... SKIPPED
[INFO] arctic-flink-1.12 .................................. SKIPPED
[INFO] arctic-flink-runtime-1.12 .......................... SKIPPED
[INFO] arctic-spark_2.3 ................................... SKIPPED
[INFO] arctic-spark_3.1-runtime ........................... SKIPPED
[INFO] dist ............................................... SKIPPED
[INFO] arctic-hive ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:40 min
[INFO] Finished at: 2022-08-04T10:16:55+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project arctic-ams-server: There are test failures.
```

**Comment by Aireed** [comment]
does the bug still exist??

**Comment by zhoujinsong** [comment]
> does the bug still exist??

cc @baiyangtx
