### ISSUE TITLE
[Improvement]: Checking the required properties when adding a new Optimizer group

### ISSUE THREAD

**Issue by wangtaohz** [apache/amoro#1690]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

After creating an optimizer group using `localContainer` without setting any properties,
<img width="514" alt="image" src="https://github.com/NetEase/arctic/assets/103108928/fbb18701-caee-4754-8803-6339de49141d">

when I scale out the optimizer group, it throws an exception
<img width="1299" alt="image" src="https://github.com/NetEase/arctic/assets/103108928/408696e8-ef41-451a-89ac-7c80f9db502e">

### How should we improve?

We should check the required properties when adding a new Optimizer group.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
```
2023-07-12 16:06:56,563 ERROR [JettyServerThreadPool-39] [com.netease.arctic.server.dashboard.DashboardServer] [] - Failed to handle request
java.lang.IllegalStateException: Cannot find memory in properties
        at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:590) ~[iceberg-bundled-guava-1.1.0.jar:?]
        at com.netease.arctic.optimizer.util.PropertyUtil.checkAndGetProperty(PropertyUtil.java:10) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.optimizer.LocalOptimizerContainer.buildOptimizerStartupArgsString(LocalOptimizerContainer.java:52) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.optimizer.AbstractResourceContainer.requestResource(AbstractResourceContainer.java:31) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.dashboard.controller.OptimizerController.scaleOutOptimizer(OptimizerController.java:208) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:98) ~[javalin-4.6.1.jar:4.6.1]
```
