### ISSUE TITLE
[Bug]: Self-Optimizing fails when it takes too long to execute 

### ISSUE THREAD

**Issue by nicochen** [apache/amoro#1790]
### What happened?

When I upgrade a hive table to Mixed Hive Table and consistently write to it with Flink, when the table spends a long time practicing Self-Optimizing, it will fail at some point.

### Affects Versions

master

### What engines are you seeing the problem on?

Optimizer

### How to reproduce

1. Upgrade a hive table to Mixed Hive Table
2. Continuously write data with flink
3. Enable Self-Optimizing

### Relevant log output

```shell
org.apache.iceberg.exceptions.NotFoundException: Failed to open input stream for file: hdfs://xxxx/user/xxxx/hive_db/xxxxx/xxxxx/change/metadata/v954.metadata.json
	at org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:185)
	at org.apache.iceberg.TableMetadataParser.read(TableMetadataParser.java:273)
	at org.apache.iceberg.TableMetadataParser.read(TableMetadataParser.java:267)
	at org.apache.iceberg.StaticTableOperations.current(StaticTableOperations.java:50)
	at org.apache.iceberg.BaseTable.schemas(BaseTable.java:94)
	at org.apache.iceberg.SerializableTable.schemas(SerializableTable.java:175)
	at com.netease.arctic.table.BasicUnkeyedTable.schemas(BasicUnkeyedTable.java:131)
	at com.netease.arctic.op.KeyedSchemaUpdate.syncSchema(KeyedSchemaUpdate.java:209)
	at com.netease.arctic.table.BasicKeyedTable.schema(BasicKeyedTable.java:78)
	at com.netease.arctic.hive.optimizing.MixFormatOptimizingDataReader.readData(MixFormatOptimizingDataReader.java:50)
	at com.netease.arctic.optimizing.AbstractRewriteFilesExecutor.rewriterDataFiles(AbstractRewriteFilesExecutor.java:144)
	at com.netease.arctic.table.TableMetaStore.doAsUgi(TableMetaStore.java:365)
	at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:345)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1734)
	at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:345)
	at com.netease.arctic.io.ArcticHadoopFileIO.doAs(ArcticHadoopFileIO.java:187)
	at com.netease.arctic.optimizing.AbstractRewriteFilesExecutor.execute(AbstractRewriteFilesExecutor.java:100)
	at com.netease.arctic.optimizing.AbstractRewriteFilesExecutor.execute(AbstractRewriteFilesExecutor.java:57)
	at com.netease.arctic.optimizer.OptimizerExecutor.executeTask(OptimizerExecutor.java:97)
	at com.netease.arctic.optimizer.OptimizerExecutor.start(OptimizerExecutor.java:34)
	at com.netease.arctic.optimizer.flink.FlinkExecutor.lambda$open$0(FlinkExecutor.java:41)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: File does not exist: /user/xxxxx/hive_db/xxxxxx/xxxxx/change/metadata/v954.metadata.json
	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:156)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:2099)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:780)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:458)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:604)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:572)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:556)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1093)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1043)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:971)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2976)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
The direct cause of the bug is that when the optimizer executes tasks, it uses a table object loaded from the plan, but the metadata file corresponding to this object has been deleted. When executing the "hive sync schema" function and calling the "schemas()" API of the change store, it will attempt to load the deleted metadata file.

It needs to be confirmed which operations in the optimizer will attempt to read the old metadata file and whether the impact is only on mixed Hive tables.

**Comment by zhoujinsong** [comment]
I think this issue may happen on the Iceberg format table too.

`org.apache.iceberg.SerializableTable` will serialize the metadata file location only and will read the metadata file when needed.

But I am curious why the optimizing task needs to load the metadata file from a long time ago during the execution process.

If we set a fresh table object (with the newest current snapshot) to the optimizing job before we pass it to the optimizer, can we solve this issue?
