### ISSUE TITLE
[Bug]: When the iceberg table is empty, clean orphan file NPE

### ISSUE THREAD

**Issue by XiaoGerGer** [apache/amoro#2426]
### What happened?

2023-12-13 01:54:44,591 ERROR [async-orphan-files-cleaning-executor-4] [com.netease.arctic.server.table.executor.OrphanFilesCleaningExecutor] [] - ice-01.ods_bps.ods_ebeb(tableId=677) failed to clean orphan file

java.lang.NullPointerException: null

         at com.netease.arctic.server.optimizing.maintainer.IcebergTableMaintainer.cleanOrphanFiles(IcebergTableMaintainer.java:140) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]

         at com.netease.arctic.server.table.executor.OrphanFilesCleaningExecutor.execute(OrphanFilesCleaningExecutor.java:61) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]

         at com.netease.arctic.server.table.executor.BaseTableExecutor.executeTask(BaseTableExecutor.java:74) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]

         at com.netease.arctic.server.table.executor.BaseTableExecutor.lambda$scheduleIfNecessary$4(BaseTableExecutor.java:83) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]

         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_392]

         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_392]

         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_392]

         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_392]

         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_392]

         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_392]

         at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]

### Affects Versions

master-snapshot [ at 2023-12-08 ]

### Relevant log output

```shell
2023-12-13 01:54:44,591 ERROR [async-orphan-files-cleaning-executor-4] [com.netease.arctic.server.table.executor.OrphanFilesCleaningExecutor] [] - ice-01.ods_bps.ods_wl_pcn_batchapplydetail(tableId=677) failed to clean orphan file

java.lang.NullPointerException: null

         at com.netease.arctic.server.optimizing.maintainer.IcebergTableMaintainer.cleanOrphanFiles(IcebergTableMaintainer.java:140) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]

         at com.netease.arctic.server.table.executor.OrphanFilesCleaningExecutor.execute(OrphanFilesCleaningExecutor.java:61) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]

         at com.netease.arctic.server.table.executor.BaseTableExecutor.executeTask(BaseTableExecutor.java:74) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]

         at com.netease.arctic.server.table.executor.BaseTableExecutor.lambda$scheduleIfNecessary$4(BaseTableExecutor.java:83) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]

         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_392]

         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_392]

         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_392]

         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_392]

         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_392]

         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_392]

         at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by klion26** [comment]
@XiaoGerGer thanks for reporting this, from the [code](https://github.com/NetEase/amoro/blob/34bb1a57cdba25579b4b015b8780f4846eb67e5e/ams/server/src/main/java/com/netease/arctic/server/optimizing/maintainer/IcebergTableMaintainer.java#L140) seems the property `table` is null, could you please share how to reproduce this error, thanks.
