### ISSUE TITLE
[Improvement]: Fix the issue of entering infinite failure

### ISSUE THREAD

**Issue by xleoken** [apache/amoro#2956]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

We deploy services ams-dashboard and ams-server separately, so I wanna build and run the amro-ams-server without dashboard, but the ams-server entering infinite failure.

```
2024-06-21 17:50:51,955 ERROR [main] [org.apache.amoro.server.AmoroServiceContainer] [] - AMS start error
io.javalin.core.util.JavalinException: Static resource directory with path: '/static' does not exist. Depending on your setup, empty folders might not get copied to classpath.
	at io.javalin.jetty.ConfigurableHandler.getResourceBase(JettyResourceHandler.kt:96) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.jetty.ConfigurableHandler.<init>(JettyResourceHandler.kt:70) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.jetty.JettyResourceHandler.addStaticFileConfig(JettyResourceHandler.kt:33) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.core.JavalinConfig.addStaticFiles(JavalinConfig.java:134) ~[javalin-4.6.8.jar:4.6.8]
	at org.apache.amoro.server.AmoroServiceContainer.lambda$initHttpService$0(AmoroServiceContainer.java:216) ~[amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at io.javalin.core.JavalinConfig.applyUserConfig(JavalinConfig.java:205) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.Javalin.create(Javalin.java:93) ~[javalin-4.6.8.jar:4.6.8]
	at org.apache.amoro.server.AmoroServiceContainer.initHttpService(AmoroServiceContainer.java:214) ~[amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at org.apache.amoro.server.AmoroServiceContainer.startService(AmoroServiceContainer.java:157) ~[amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at org.apache.amoro.server.AmoroServiceContainer.main(AmoroServiceContainer.java:108) [amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
2024-06-21 17:50:51,956 ERROR [terminal-session-gc] [org.apache.amoro.server.terminal.TerminalManager] [] - Interrupted when sleep
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method) ~[?:1.8.0_202]
	at java.lang.Thread.sleep(Thread.java:340) ~[?:1.8.0_202]
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386) ~[?:1.8.0_202]
	at org.apache.amoro.server.terminal.TerminalManager$SessionCleanTask.run(TerminalManager.java:414) [amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
2024-06-21 17:50:51,964 ERROR [main] [org.apache.amoro.server.AmoroServiceContainer] [] - AMS start error
io.javalin.core.util.JavalinException: Static resource directory with path: '/static' does not exist. Depending on your setup, empty folders might not get copied to classpath.
	at io.javalin.jetty.ConfigurableHandler.getResourceBase(JettyResourceHandler.kt:96) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.jetty.ConfigurableHandler.<init>(JettyResourceHandler.kt:70) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.jetty.JettyResourceHandler.addStaticFileConfig(JettyResourceHandler.kt:33) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.core.JavalinConfig.addStaticFiles(JavalinConfig.java:134) ~[javalin-4.6.8.jar:4.6.8]
	at org.apache.amoro.server.AmoroServiceContainer.lambda$initHttpService$0(AmoroServiceContainer.java:216) ~[amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at io.javalin.core.JavalinConfig.applyUserConfig(JavalinConfig.java:205) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.Javalin.create(Javalin.java:93) ~[javalin-4.6.8.jar:4.6.8]
	at org.apache.amoro.server.AmoroServiceContainer.initHttpService(AmoroServiceContainer.java:214) ~[amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at org.apache.amoro.server.AmoroServiceContainer.startService(AmoroServiceContainer.java:157) ~[amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at org.apache.amoro.server.AmoroServiceContainer.main(AmoroServiceContainer.java:108) [amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
2024-06-21 17:50:51,965 ERROR [terminal-session-gc] [org.apache.amoro.server.terminal.TerminalManager] [] - Interrupted when sleep
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method) ~[?:1.8.0_202]
	at java.lang.Thread.sleep(Thread.java:340) ~[?:1.8.0_202]
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386) ~[?:1.8.0_202]
	at org.apache.amoro.server.terminal.TerminalManager$SessionCleanTask.run(TerminalManager.java:414) [amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
2024-06-21 17:50:51,971 ERROR [main] [org.apache.amoro.server.AmoroServiceContainer] [] - AMS start error
io.javalin.core.util.JavalinException: Static resource directory with path: '/static' does not exist. Depending on your setup, empty folders might not get copied to classpath.
	at io.javalin.jetty.ConfigurableHandler.getResourceBase(JettyResourceHandler.kt:96) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.jetty.ConfigurableHandler.<init>(JettyResourceHandler.kt:70) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.jetty.JettyResourceHandler.addStaticFileConfig(JettyResourceHandler.kt:33) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.core.JavalinConfig.addStaticFiles(JavalinConfig.java:134) ~[javalin-4.6.8.jar:4.6.8]
	at org.apache.amoro.server.AmoroServiceContainer.lambda$initHttpService$0(AmoroServiceContainer.java:216) ~[amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at io.javalin.core.JavalinConfig.applyUserConfig(JavalinConfig.java:205) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.Javalin.create(Javalin.java:93) ~[javalin-4.6.8.jar:4.6.8]
	at org.apache.amoro.server.AmoroServiceContainer.initHttpService(AmoroServiceContainer.java:214) ~[amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at org.apache.amoro.server.AmoroServiceContainer.startService(AmoroServiceContainer.java:157) ~[amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at org.apache.amoro.server.AmoroServiceContainer.main(AmoroServiceContainer.java:108) [amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
2024-06-21 17:50:51,972 ERROR [terminal-session-gc] [org.apache.amoro.server.terminal.TerminalManager] [] - Interrupted when sleep
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method) ~[?:1.8.0_202]
	at java.lang.Thread.sleep(Thread.java:340) ~[?:1.8.0_202]
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386) ~[?:1.8.0_202]
	at org.apache.amoro.server.terminal.TerminalManager$SessionCleanTask.run(TerminalManager.java:414) [amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
2024-06-21 17:50:51,995 ERROR [main] [org.apache.amoro.server.AmoroServiceContainer] [] - AMS start error
io.javalin.core.util.JavalinException: Static resource directory with path: '/static' does not exist. Depending on your setup, empty folders might not get copied to classpath.
	at io.javalin.jetty.ConfigurableHandler.getResourceBase(JettyResourceHandler.kt:96) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.jetty.ConfigurableHandler.<init>(JettyResourceHandler.kt:70) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.jetty.JettyResourceHandler.addStaticFileConfig(JettyResourceHandler.kt:33) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.core.JavalinConfig.addStaticFiles(JavalinConfig.java:134) ~[javalin-4.6.8.jar:4.6.8]
	at org.apache.amoro.server.AmoroServiceContainer.lambda$initHttpService$0(AmoroServiceContainer.java:216) ~[amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at io.javalin.core.JavalinConfig.applyUserConfig(JavalinConfig.java:205) ~[javalin-4.6.8.jar:4.6.8]
	at io.javalin.Javalin.create(Javalin.java:93) ~[javalin-4.6.8.jar:4.6.8]
	at org.apache.amoro.server.AmoroServiceContainer.initHttpService(AmoroServiceContainer.java:214) ~[amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at org.apache.amoro.server.AmoroServiceContainer.startService(AmoroServiceContainer.java:157) ~[amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at org.apache.amoro.server.AmoroServiceContainer.main(AmoroServiceContainer.java:108) [amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
2024-06-21 17:50:51,996 ERROR [terminal-session-gc] [org.apache.amoro.server.terminal.TerminalManager] [] - Interrupted when sleep
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method) ~[?:1.8.0_202]
	at java.lang.Thread.sleep(Thread.java:340) ~[?:1.8.0_202]
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386) ~[?:1.8.0_202]
	at org.apache.amoro.server.terminal.TerminalManager$SessionCleanTask.run(TerminalManager.java:414) [amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klion26** [comment]
I ran into this problem when starting AMS locally(0.7.x), and fixed it after compiling the whole project

The whole compile will generate the asserts such as below
![image](https://github.com/user-attachments/assets/b4802f8c-b696-4fb7-bd9a-d45b7957ee8e)
