### ISSUE TITLE
[Bug]: Optimization state blocking in running

### ISSUE THREAD

**Issue by rfyu** [apache/amoro#3110]
### What happened?

When the insertion into table `optimizing_task_quota` fails, subsequent logic cannot proceed because all database operations are wrapped in the same session. Even if the exception is caught, `com.netease.arctic.server.persistence.NestedSqlSession#isRollingback` will still be true.Therefore, an exception will be thrown when checking the session status in `org.apache.amoro.server.persistence.NestedSqlSession#checkState`. So the table optimization status is stuck in running.

### Affects Versions

master

### What table formats are you seeing the problem on?

Iceberg

### What engines are you seeing the problem on?

AMS

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XBaith** [comment]
I also meet same error, the exception log is:
```
2024-08-21 18:00:51,104 ERROR [thrift-server-optimize-manager-1738] [org.apache.amoro.server.optimizing.OptimizingQueue] [] - accept result error:
org.apache.amoro.server.exception.PersistenceException: org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'fail_reason' at row 1
### The error may exist in org/apache/amoro/server/persistence/mapper/OptimizingMapper.java (best guess)
### The error may involve org.apache.amoro.server.persistence.mapper.OptimizingMapper.updateOptimizingProcess-Inline
### The error occurred while setting parameters
### SQL: UPDATE table_optimizing_process SET status = ?, end_time = ?, summary = ?, fail_reason = ? WHERE table_id = ? AND process_id = ?
### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'fail_reason' at row 1
	at org.apache.amoro.server.exception.AmoroRuntimeException.wrap(AmoroRuntimeException.java:141) ~[amoro-ams-server-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.amoro.server.persistence.PersistentBase.doAs(PersistentBase.java:53) ~[amoro-ams-server-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.amoro.server.optimizing.OptimizingQueue.access$600(OptimizingQueue.java:73) ~[amoro-ams-server-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.amoro.server.optimizing.OptimizingQueue$TableOptimizingProcess.lambda$persistProcessCompleted$11(OptimizingQueue.java:645) ~[amoro-ams-server-0.7.0-incubating.jar:0.7.0-incubating]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_422]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_422]
	at org.apache.amoro.server.persistence.PersistentBase.doAsTransaction(PersistentBase.java:61) ~[amoro-ams-server-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.amoro.server.optimizing.OptimizingQueue.access$400(OptimizingQueue.java:73) ~[amoro-ams-server-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.amoro.server.optimizing.OptimizingQueue$TableOptimizingProcess.persistProcessCompleted(OptimizingQueue.java:643) ~[amoro-ams-server-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.amoro.server.optimizing.OptimizingQueue$TableOptimizingProcess.acceptResult(OptimizingQueue.java:466) ~[amoro-ams-server-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.amoro.server.optimizing.TaskRuntime.lambda$complete$0(TaskRuntime.java:104) ~[amoro-ams-server-0.7.0-incubating.jar:0.7.0-incubating]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) [?:1.8.0_422]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) [?:1.8.0_422]
	at org.apache.amoro.server.persistence.PersistentBase.doAsTransaction(PersistentBase.java:61) [amoro-ams-server-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.amoro.server.persistence.StatedPersistentBase.invokeConsistency(StatedPersistentBase.java:51) [amoro-ams-server-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.amoro.server.optimizing.TaskRuntime.complete(TaskRuntime.java:77) [amoro-ams-server-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.amoro.server.DefaultOptimizingService.completeTask(DefaultOptimizingService.java:234) [amoro-ams-server-0.7.0-incubating.jar:0.7.0-incubating]
	at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_422]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_422]
	at org.apache.amoro.server.utils.ThriftServiceProxy.invoke(ThriftServiceProxy.java:56) [amoro-ams-server-0.7.0-incubating.jar:0.7.0-incubating]
	at com.sun.proxy.$Proxy48.completeTask(Unknown Source) [?:?]
	at org.apache.amoro.api.OptimizingService$Processor$completeTask.getResult(OptimizingService.java:629) [amoro-core-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.amoro.api.OptimizingService$Processor$completeTask.getResult(OptimizingService.java:605) [amoro-core-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.amoro.shade.thrift.org.apache.thrift.ProcessFunction.process(ProcessFunction.java:40) [amoro-shade-thrift-0.20.0-0.7-SNAPSHOT.jar:0.20.0-0.7-SNAPSHOT]
	at org.apache.amoro.shade.thrift.org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:40) [amoro-shade-thrift-0.20.0-0.7-SNAPSHOT.jar:0.20.0-0.7-SNAPSHOT]
	at org.apache.amoro.shade.thrift.org.apache.thrift.TMultiplexedProcessor.process(TMultiplexedProcessor.java:147) [amoro-shade-thrift-0.20.0-0.7-SNAPSHOT.jar:0.20.0-0.7-SNAPSHOT]
	at org.apache.amoro.shade.thrift.org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:492) [amoro-shade-thrift-0.20.0-0.7-SNAPSHOT.jar:0.20.0-0.7-SNAPSHOT]
	at org.apache.amoro.shade.thrift.org.apache.thrift.server.Invocation.run(Invocation.java:19) [amoro-shade-thrift-0.20.0-0.7-SNAPSHOT.jar:0.20.0-0.7-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_422]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_422]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_422]
```

I will rise another PR to fix this.

**Comment by rfyu** [comment]
Mabey your problem can be solved by throwing this exception and expanding the field type.WDYT? @XBaith

**Comment by XBaith** [comment]
> Mabey your problem can be solved by throwing this exception and expanding the field type.WDYT? @XBaith

This may alleviate the problem, but limiting the size of the error message may solve the underlying problem.

**Comment by rfyu** [comment]
> > Mabey your problem can be solved by throwing this exception and expanding the field type.WDYT? @XBaith
> 
> This may alleviate the problem, but limiting the size of the error message may solve the underlying problem.

Makes sense, you're right.
