### ISSUE TITLE
[Bug]: Click snapshotId cannot be displayed normally

### ISSUE THREAD

**Issue by zhongqishang** [apache/amoro#3149]
### What happened?

![image](https://github.com/user-attachments/assets/e7866da0-c0f0-447c-946b-abcaac43858d)

### Affects Versions

master

### What table formats are you seeing the problem on?

Iceberg

### What engines are you seeing the problem on?

AMS

### Relevant log output

```shell
java.lang.IllegalArgumentException: unknown snapshot 9029332474947663360 of iceberg.ods_iceberg.gen_sink_olap_test
	at org.apache.amoro.server.dashboard.MixedAndIcebergTableDescriptor.getSnapshotDetail(MixedAndIcebergTableDescriptor.java:354) ~[classes/:?]
	at org.apache.amoro.server.dashboard.ServerTableDescriptor.getSnapshotDetail(ServerTableDescriptor.java:86) ~[classes/:?]
	at org.apache.amoro.server.dashboard.controller.TableController.getSnapshotDetail(TableController.java:398) ~[classes/:?]
```

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhongqishang** [comment]
The method `org.apache.amoro.table.descriptor.FormatTableDescriptor#getSnapshotDetail` parameter type changes caused by. 
@baiyangtx `snapshotId` need change to long?
