### ISSUE TITLE
[Bug]: Planning table failed, java.lang.StackOverflowError: null

### ISSUE THREAD

**Issue by lintingbin** [apache/amoro#3239]
### What happened?

When amoro executes planning with many partitions (over 20,000 in my case) and needs compression, a "StackOverflowError" occurs. Using the official iceberg rewrite_data_files does not have this issue.

### Affects Versions

0.7.0

### What table formats are you seeing the problem on?

Iceberg

### What engines are you seeing the problem on?

AMS

### Relevant log output

```shell
2024-10-09 07:39:05,651 ERROR [plan-executor-thread-37916] [org.apache.amoro.server.optimizing.OptimizingQueue] [] - Planning table hive.test.mytable(tableId=672) failed
java.lang.StackOverflowError: null
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:356) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:369) ~[iceberg-api-1.4.3.jar:?]
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 7hong** [comment]
I had the same problem, and I resolved it by limiting the number of partitions read in the filter。
I will submit a pr later

**Comment by majin1102** [comment]
> I had the same problem, and I resolved it by limiting the number of partitions read in the filter。 I will submit a pr later

I left comments in your PR, PTAL
