### ISSUE TITLE
[Bug]: No enum constant org.apache.amoro.process.ProcessStatus.ACTIVE

### ISSUE THREAD

**Issue by zhongqishang** [apache/amoro#3295]
### What happened?

We don't have the `ACTIVE` state, so we need to delete it from the frontend page.

### Affects Versions

master

### What table formats are you seeing the problem on?

Iceberg

### What engines are you seeing the problem on?

AMS

### How to reproduce

![image](https://github.com/user-attachments/assets/d077ef10-29fb-48cd-bde5-3979abb96d7a)

### Relevant log output

```
2024-10-23 19:41:56,912 ERROR [JettyServerThreadPool-65] [org.apache.amoro.server.dashboard.DashboardServer] [] - An error occurred while processing the url:http://localhost:1630/api/ams/v1/tables/catalogs/iceberg/dbs/ods_iceberg/tables/products/optimizing-processes
java.lang.IllegalArgumentException: No enum constant org.apache.amoro.process.ProcessStatus.ACTIVE
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_331]
	at org.apache.amoro.process.ProcessStatus.valueOf(ProcessStatus.java:22) ~[classes/:?]
	at org.apache.amoro.server.dashboard.controller.TableController.getOptimizingProcesses(TableController.java:330) ~[classes/:?]
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20) ~[javalin-4.6.8.jar:4.6.8]
	...
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhongqishang** [comment]
close in #3298
