### ISSUE TITLE
[Improvement]: Object Serialization Optimization and Support

### ISSUE THREAD

**Issue by czy006** [apache/amoro#3355]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, we use **Java serialization** and **Kyro serialization**. This serialization method may have some issues, including low performance, We use Kyro serialization for **PUT** and **GET** operations on Rocksdb, which is a lookup join feature in **Mixed Format**

In the objects we store in the database, we also need to serialize and deserialize. During the upgrade process, we occasionally encounter deserialization errors and issues (as shown in the figure below)

Through research, we found that **[Apache Fury](https://fury.apache.org/)** can improve serialization performance and solve deserialization problems. We will provide performance testing reports in the future to compare before and after replacement

### How should we improve?

- Abstract resource serialization interface, implementation of native serialization in current Java, implementation of Kyro serialization
- Implement Fury serialization and provide configuration options for Fury serialization, while marking other serialization methods as expired
- When the Amoro LTS version is completed, we will remove the implementation of Kyro serialization

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czy006** [comment]
```
java.lang.IllegalArgumentException: deserialization error 
	at org.apache.amoro.utils.SerializationUtil.simpleDeserialize(SerializationUtil.java:68)
	at org.apache.amoro.optimizer.spark.SparkOptimizerExecutor.jobDescription(SparkOptimizerExecutor.java:85)
	at org.apache.amoro.optimizer.spark.SparkOptimizerExecutor.executeTask(SparkOptimizerExecutor.java:58)
	at org.apache.amoro.optimizer.common.OptimizerExecutor.start(OptimizerExecutor.java:53)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.InvalidClassException: org.apache.iceberg.BaseFile; local class incompatible: stream classdesc serialVersionUID = 4493876333706690896, local class serialVersionUID = -6272254142325460014
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:687)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1883)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1749)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1883)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1749)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2040)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1571)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1973)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1565)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2285)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2209)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2067)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1571)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at org.apache.amoro.utils.SerializationUtil.simpleDeserialize(SerializationUtil.java:65)
	... 4 more
```

**Comment by ihadoop** [comment]
i think json is the best way for object serialization. it can be parsed by any language.
